# Site settings
title: lzw-723's Blog
SEOTitle:  lzw-723's Blog
email: lzw-723@qq.com
keyword: "lzw-723"
url: "https://lzw-723.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'

encoding: utf-8

RSS: true

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`