# Site settings
title: lzw-723's Blog
SEOTitle:  lzw-723's Blog
email: lzw-723@qq.com
keyword: "lzw-723"
url: "https://lzw-723.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'

encoding: utf-8

RSS: true

paginate: 10

# Friends
friends: [
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
]


theme: jekyll-theme-cayman